# -*- coding: utf-8 -*-
"""Copy of aeso_api_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16LztfJ9ZUwPMGfpmyA07HaoMjLQ-ODyF

**AESO API SCRIPT FILE**
"""

# Import Pool

import pandas as pd  # Importing Pandas as 'pd'
import requests      # Importing Requests (Used for REST APIs GET Calls)
import json          # Importing JSON Libary/Module (Probably Redunant in Colab?)
import time          # Importing

from datetime import datetime, timedelta  # -------------- TO DO

# Establishing Access Tokens for AESO API Access

api_prim = '48e62c31b31044b5bf3d48a951f44c1a'   # This is the Primary API Access Token Key (Danny's Portal)
api_sec = '6269977561a944e3b58e2268b1346d34'    # This is the Secondary API Access Token Key (Danny's Portal)


# Establishing (Relevant) API Endpoint URLs

capacity_url = 'https://apimgw.aeso.ca/public/aiesgencapacity-api/v1/AIESGenCapacity'                         # Accessing the AESO Gen. Capacity API Endpoint
forecast_url = 'https://apimgw.aeso.ca/public/actualforecast-api/v1/load/albertaInternalLoad'                 # Accessing the AESO Forecast Report API Endpoint
supplydemand_url = 'https://apimgw.aeso.ca/public/currentsupplydemand-api/v2/csd/summary/current'             # Accessing the AESO Supply & Demand (V2) Report API Endpoint
assets_url = 'https://apimgw.aeso.ca/public/assetlist-api/v1/assetlist'                                       # Accessing the AESO Assets List API Endpoint
meter_url = 'https://apimgw.aeso.ca/public/meteredvolume-api/v1/meteredvolume/details'                        # Accessing the AESO Metered Volume (V1) Report API Endpoint
merit_url = 'https://apimgw.aeso.ca/public/energymeritorder-api/v1/meritOrder/energy'                         # Accessing the AESO Ordered Energy Merit Report API Endpoint
load_outage_url = 'https://apimgw.aeso.ca/public/loadoutageforecast-api/v1/loadOutageReport'                  # Accessing the AESO Load Outage Forecast Report API Endpoint
pool_list_url = 'https://apimgw.aeso.ca/public/PoolParticipant-api/v1/poolparticipantlist'                    # Accessing the AESO Pool Participant List API Endpoint
pool_price_url = 'https://apimgw.aeso.ca/public/poolprice-api/v1.1/price/poolPrice'                           # Accessing the AESO Pool Price Reports API Endpoint
marginal_url = 'https://apimgw.aeso.ca/public/systemmarginalprice-api/v1.1/price/systemMarginalPrice' # Accessing the AESO System Marginal Price Reports API Endpoint


# Creating Parameters for API Requests

"""
api_params = {                        // This is commented out for now, the initial API Calls do not need parameters to pass through until Metered Volume and onward.
    'startDate': '2018-01-01',
    'endDate': '2018-01-31'
    }
    """

# Creating the Header for AESO API Key Access

headers = {
    "API-KEY": api_prim   # Using the Primary Access Key
}

"""##AESO Actual Forecast Report REST API Code Block"""

# Setting Up the REST API Code Block for AESO Data Scraping

data_start_date = datetime(2011, 1, 1)                 # Establishing the Start Date (Start Collecting Data from this Date -- Year, Month, Day)
data_end_date = datetime(2026, 2, 26)                  # Establishing the End Date (Stop Collecting Data at this Date -- Year, Month, Day)

fc_data_bucket = []                                    # Creating a Data Bucket to Store from API Outputs (In this case Data from Actual Forecast Report)

current_date = data_start_date                         # Current 'Indexer' for the Dates. Date-Index Begins at Established Start Date

while current_date < data_end_date:                    # While Loop to Automate Multiple-API Requests for Data

  current_end = current_date + timedelta(days=30)      # This Establishes the 'endDate' Parameter for the API Request (End Date is 30 Days after Start Date)

  if current_end > data_end_date:                      # If Condition Made to Clamp Down on 'Date Out of Bounds Error' (aka - do not go beyond the established end date)
    current_end = data_end_date                        # If the index is beyond the end date then clamp down the index to the end date itself which will terminate the loop

  api_params = {                                       # This Dictionary Holds Required API Parameters Used for Requests
      'startDate': current_date.strftime("%Y-%m-%d"),  # Parameter Input - Current Date the Indexer is on
      'endDate': current_end.strftime("%Y-%m-%d")      # Parameter Input - End Date to get data from (30 days from start)
  }

  api_response = requests.get(forecast_url, headers=headers, params=api_params)    # Calling the Assets Endpoint URL with GET to Obtain AESO Actual Forecast Reports (2011-2026)

  print("API Call STATUS CODE --", api_response.status_code)                       # Printing Out the GET Request Status Code (200 = Good | Else = Didn't Work)

  if api_response.status_code != 200:                                     # If Condition Made to Catch Request-Errors
    print(api_response.text)                                              # If There's a Request Error then this will print out why there is an error

  else:                                                                   # Else-Branch - Code comes back 200, request is good, data is coming in
    print("Throwing Data into Bucket")                                    # Re-Assuring the User that It is indeed working
    api_data = api_response.json()                                        # API Response is converted to JSON format and stored in variable
    fc_data_bucket.extend(api_data['return']['Actual Forecast Report'])   # Data Entries from API Output to JSON is Stored in a Data Collections Bucket

  time.sleep(3)                                                           # Time Delay Established to Not Overwhelm the API Endpoint from Massive Request Calls (3 Second Delay per Request)

  current_date = current_end + timedelta(days=1)                          # Current Index Date Advances by 1-Day before the next batch request

  print(api_params)                                                       # DEBUGGING PURPOSES ONLY -- Just Checking to see if the Date Iteration Actually Works as Intended

fc_data_bucket

df_forecast = pd.DataFrame(fc_data_bucket)

df_forecast

df_forecast.to_csv("aeso_actual_forecast_report.csv", index = False)

"""##AIES/AESO Generation Capacity Report REST API Code Block"""

# Setting Up the REST API Code Block for AESO Data Scraping

data_start_date = datetime(2011, 1, 1)                 # Establishing the Start Date (Start Collecting Data from this Date -- Year, Month, Day)
data_end_date = datetime(2026, 2, 26)                  # Establishing the End Date (Stop Collecting Data at this Date -- Year, Month, Day)

gc_data_bucket = []                                    # Creating a Data Bucket to Store from API Outputs (In this case Data from Actual Forecast Report)

current_date = data_start_date                         # Current 'Indexer' for the Dates. Date-Index Begins at Established Start Date

while current_date < data_end_date:                    # While Loop to Automate Multiple-API Requests for Data

  current_end = current_date + timedelta(days=30)      # This Establishes the 'endDate' Parameter for the API Request (End Date is 30 Days after Start Date)

  if current_end > data_end_date:                      # If Condition Made to Clamp Down on 'Date Out of Bounds Error' (aka - do not go beyond the established end date)
    current_end = data_end_date                        # If the index is beyond the end date then clamp down the index to the end date itself which will terminate the loop

  api_params = {                                       # This Dictionary Holds Required API Parameters Used for Requests
      'startDate': current_date.strftime("%Y-%m-%d"),  # Parameter Input - Current Date the Indexer is on
      'endDate': current_end.strftime("%Y-%m-%d")      # Parameter Input - End Date to get data from (30 days from start)
  }

  api_response = requests.get(capacity_url, headers=headers, params=api_params)    # Calling the Assets Endpoint URL with GET to Obtain AESO Actual Forecast Reports (2011-2026)

  print("API Call STATUS CODE --", api_response.status_code)                       # Printing Out the GET Request Status Code (200 = Good | Else = Didn't Work)

  if api_response.status_code != 200:                                     # If Condition Made to Catch Request-Errors
    print(api_response.text)                                              # If There's a Request Error then this will print out why there is an error

  else:                                                                   # Else-Branch - Code comes back 200, request is good, data is coming in
    print("Throwing Data into Bucket")                                    # Re-Assuring the User that It is indeed working
    api_data = api_response.json()                                        # API Response is converted to JSON format and stored in variable
    gc_data_bucket.extend(api_data['return'])                             # Data Entries from API Output to JSON is Stored in a Data Collections Bucket

  time.sleep(3)                                                           # Time Delay Established to Not Overwhelm the API Endpoint from Massive Request Calls (3 Second Delay per Request)

  current_date = current_end + timedelta(days=1)                          # Current Index Date Advances by 1-Day before the next batch request

  print(api_params)                                                       # DEBUGGING PURPOSES ONLY -- Just Checking to see if the Date Iteration Actually Works as Intended

gc_data_bucket

df_capacity = pd.json_normalize(gc_data_bucket, record_path='Hours', meta=['fuel_type', 'sub_fuel_type'])

df_capacity

df_capacity.to_csv("aeso_gen_cap_outages.csv", index = False)

"""##AESO Load Outage Forecast Report REST API Code Block"""

# Setting Up the REST API Code Block for AESO Data Scraping

data_start_date = datetime(2013, 9, 22)                 # Establishing the Start Date (Start Collecting Data from this Date -- Year, Month, Day)
data_end_date = datetime(2026, 2, 26)                  # Establishing the End Date (Stop Collecting Data at this Date -- Year, Month, Day)

lof_data_bucket = []                                    # Creating a Data Bucket to Store from API Outputs (In this case Data from Actual Forecast Report)

current_date = data_start_date                         # Current 'Indexer' for the Dates. Date-Index Begins at Established Start Date

while current_date < data_end_date:                    # While Loop to Automate Multiple-API Requests for Data

  current_end = current_date + timedelta(days=30)      # This Establishes the 'endDate' Parameter for the API Request (End Date is 30 Days after Start Date)

  if current_end > data_end_date:                      # If Condition Made to Clamp Down on 'Date Out of Bounds Error' (aka - do not go beyond the established end date)
    current_end = data_end_date                        # If the index is beyond the end date then clamp down the index to the end date itself which will terminate the loop

  api_params = {                                       # This Dictionary Holds Required API Parameters Used for Requests
      'startDate': current_date.strftime("%Y-%m-%d"),  # Parameter Input - Current Date the Indexer is on
      'endDate': current_end.strftime("%Y-%m-%d")      # Parameter Input - End Date to get data from (30 days from start)
  }

  api_response = requests.get(load_outage_url, headers=headers, params=api_params)    # Calling the Assets Endpoint URL with GET to Obtain AESO Actual Forecast Reports (2011-2026)

  print("API Call STATUS CODE --", api_response.status_code)                       # Printing Out the GET Request Status Code (200 = Good | Else = Didn't Work)

  if api_response.status_code != 200:                                     # If Condition Made to Catch Request-Errors
    print(api_response.text)                                              # If There's a Request Error then this will print out why there is an error

  else:                                                                   # Else-Branch - Code comes back 200, request is good, data is coming in
    print("Throwing Data into Bucket")                                    # Re-Assuring the User that It is indeed working
    api_data = api_response.json()                                        # API Response is converted to JSON format and stored in variable
    lof_data_bucket.extend(api_data['return']['loadOutagePerHourVO'])     # Data Entries from API Output to JSON is Stored in a Data Collections Bucket

  time.sleep(3)                                                           # Time Delay Established to Not Overwhelm the API Endpoint from Massive Request Calls (3 Second Delay per Request)

  current_date = current_end + timedelta(days=1)                          # Current Index Date Advances by 1-Day before the next batch request

  print(api_params)                                                       # DEBUGGING PURPOSES ONLY -- Just Checking to see if the Date Iteration Actually Works as Intended

lof_data_bucket

df_lof = pd.DataFrame(lof_data_bucket)

df_lof

df_lof.to_csv("aeso_load_outage_forecast.csv", index = False)

"""##AESO Volume Metered Report REST API Code Block - Data Collection Needed"""

# Setting Up the REST API Code Block for AESO Data Scraping

data_start_date = datetime(2011, 1, 1)                 # Establishing the Start Date (Start Collecting Data from this Date -- Year, Month, Day)
data_end_date = datetime(2026, 2, 26)                  # Establishing the End Date (Stop Collecting Data at this Date -- Year, Month, Day)

meter_data_bucket = []                                    # Creating a Data Bucket to Store from API Outputs (In this case Data from Actual Forecast Report)

current_date = data_start_date                         # Current 'Indexer' for the Dates. Date-Index Begins at Established Start Date

while current_date < data_end_date:                    # While Loop to Automate Multiple-API Requests for Data

  current_end = current_date + timedelta(days=15)      # This Establishes the 'endDate' Parameter for the API Request (End Date is 30 Days after Start Date)

  if current_end > data_end_date:                      # If Condition Made to Clamp Down on 'Date Out of Bounds Error' (aka - do not go beyond the established end date)
    current_end = data_end_date                        # If the index is beyond the end date then clamp down the index to the end date itself which will terminate the loop

  api_params = {                                       # This Dictionary Holds Required API Parameters Used for Requests
      'startDate': current_date.strftime("%Y-%m-%d"),  # Parameter Input - Current Date the Indexer is on
      'endDate': current_end.strftime("%Y-%m-%d")      # Parameter Input - End Date to get data from (30 days from start)
  }

  api_response = requests.get(meter_url, headers=headers, params=api_params)    # Calling the Assets Endpoint URL with GET to Obtain AESO Actual Forecast Reports (2011-2026)

  print("API Call STATUS CODE --", api_response.status_code)                       # Printing Out the GET Request Status Code (200 = Good | Else = Didn't Work)

  if api_response.status_code != 200:                                     # If Condition Made to Catch Request-Errors
    print(api_response.text)                                              # If There's a Request Error then this will print out why there is an error

  else:                                                                   # Else-Branch - Code comes back 200, request is good, data is coming in
    print("Throwing Data into Bucket")                                    # Re-Assuring the User that It is indeed working
    api_data = api_response.json()                                        # API Response is converted to JSON format and stored in variable
    meter_data_bucket.extend(api_data['return'])   # Data Entries from API Output to JSON is Stored in a Data Collections Bucket

  time.sleep(3)                                                           # Time Delay Established to Not Overwhelm the API Endpoint from Massive Request Calls (3 Second Delay per Request)

  current_date = current_end + timedelta(days=1)                          # Current Index Date Advances by 1-Day before the next batch request

  print(api_params)                                                       # DEBUGGING PURPOSES ONLY -- Just Checking to see if the Date Iteration Actually Works as Intended

df_metered = pd.json_normalize(
    meter_data_bucket,
    record_path=['asset_list', 'metered_volume_list'],
    meta=['pool_participant_ID', ['asset_list', 'asset_ID'], ['asset_list', 'asset_class']])

meter_data_bucket[:5]

df_metered

# CODE HERE TO EXPORT TO CSV

"""##AESO Pool Price Reports REST API Code Block"""

# Setting Up the REST API Code Block for AESO Data Scraping

data_start_date = datetime(2011, 1, 1)                 # Establishing the Start Date (Start Collecting Data from this Date -- Year, Month, Day)
data_end_date = datetime(2026, 2, 26)                  # Establishing the End Date (Stop Collecting Data at this Date -- Year, Month, Day)

price_data_bucket = []                                    # Creating a Data Bucket to Store from API Outputs (In this case Data from Actual Forecast Report)

current_date = data_start_date                         # Current 'Indexer' for the Dates. Date-Index Begins at Established Start Date

while current_date < data_end_date:                    # While Loop to Automate Multiple-API Requests for Data

  current_end = current_date + timedelta(days=100)      # This Establishes the 'endDate' Parameter for the API Request (End Date is 30 Days after Start Date)

  if current_end > data_end_date:                      # If Condition Made to Clamp Down on 'Date Out of Bounds Error' (aka - do not go beyond the established end date)
    current_end = data_end_date                        # If the index is beyond the end date then clamp down the index to the end date itself which will terminate the loop

  api_params = {                                       # This Dictionary Holds Required API Parameters Used for Requests
      'startDate': current_date.strftime("%Y-%m-%d"),  # Parameter Input - Current Date the Indexer is on
      'endDate': current_end.strftime("%Y-%m-%d")      # Parameter Input - End Date to get data from (30 days from start)
  }

  api_response = requests.get(pool_price_url, headers=headers, params=api_params)    # Calling the Assets Endpoint URL with GET to Obtain AESO Actual Forecast Reports (2011-2026)

  print("API Call STATUS CODE --", api_response.status_code)                       # Printing Out the GET Request Status Code (200 = Good | Else = Didn't Work)

  if api_response.status_code != 200:                                     # If Condition Made to Catch Request-Errors
    print(api_response.text)                                              # If There's a Request Error then this will print out why there is an error

  else:                                                                   # Else-Branch - Code comes back 200, request is good, data is coming in
    print("Throwing Data into Bucket")                                    # Re-Assuring the User that It is indeed working
    api_data = api_response.json()                                        # API Response is converted to JSON format and stored in variable
    price_data_bucket.extend(api_data['return']['Pool Price Report'])     # Data Entries from API Output to JSON is Stored in a Data Collections Bucket

  time.sleep(3)                                                           # Time Delay Established to Not Overwhelm the API Endpoint from Massive Request Calls (3 Second Delay per Request)

  current_date = current_end + timedelta(days=1)                          # Current Index Date Advances by 1-Day before the next batch request

  print(api_params)                                                       # DEBUGGING PURPOSES ONLY -- Just Checking to see if the Date Iteration Actually Works as Intended

price_data_bucket

df_price = pd.DataFrame(price_data_bucket)

df_price

df_price.to_csv("aeso_pool_price_reports.csv", index = False)

"""##AESO Active System Marginal Price Reports REST API Code Block"""

# Setting Up the REST API Code Block for AESO Data Scraping

data_start_date = datetime(2011, 1, 1)                 # Establishing the Start Date (Start Collecting Data from this Date -- Year, Month, Day)
data_end_date = datetime(2026, 2, 26)                  # Establishing the End Date (Stop Collecting Data at this Date -- Year, Month, Day)

margin_data_bucket = []                                    # Creating a Data Bucket to Store from API Outputs (In this case Data from Actual Forecast Report)

current_date = data_start_date                         # Current 'Indexer' for the Dates. Date-Index Begins at Established Start Date

while current_date < data_end_date:                    # While Loop to Automate Multiple-API Requests for Data

  current_end = current_date + timedelta(days=100)      # This Establishes the 'endDate' Parameter for the API Request (End Date is 30 Days after Start Date)

  if current_end > data_end_date:                      # If Condition Made to Clamp Down on 'Date Out of Bounds Error' (aka - do not go beyond the established end date)
    current_end = data_end_date                        # If the index is beyond the end date then clamp down the index to the end date itself which will terminate the loop

  api_params = {                                       # This Dictionary Holds Required API Parameters Used for Requests
      'startDate': current_date.strftime("%Y-%m-%d"),  # Parameter Input - Current Date the Indexer is on
      'endDate': current_end.strftime("%Y-%m-%d")      # Parameter Input - End Date to get data from (30 days from start)
  }

  api_response = requests.get(marginal_url, headers=headers, params=api_params)    # Calling the Assets Endpoint URL with GET to Obtain AESO Actual Forecast Reports (2011-2026)

  print("API Call STATUS CODE --", api_response.status_code)                       # Printing Out the GET Request Status Code (200 = Good | Else = Didn't Work)

  if api_response.status_code != 200:                                     # If Condition Made to Catch Request-Errors
    print(api_response.text)                                              # If There's a Request Error then this will print out why there is an error

  else:                                                                   # Else-Branch - Code comes back 200, request is good, data is coming in
    print("Throwing Data into Bucket")                                    # Re-Assuring the User that It is indeed working
    api_data = api_response.json()                                        # API Response is converted to JSON format and stored in variable
    margin_data_bucket.extend(api_data['return']['System Marginal Price Report'])    # Data Entries from API Output to JSON is Stored in a Data Collections Bucket

  time.sleep(3)                                                           # Time Delay Established to Not Overwhelm the API Endpoint from Massive Request Calls (3 Second Delay per Request)

  current_date = current_end + timedelta(days=1)                          # Current Index Date Advances by 1-Day before the next batch request

  print(api_params)                                                       # DEBUGGING PURPOSES ONLY -- Just Checking to see if the Date Iteration Actually Works as Intended

margin_data_bucket[:5]

df_marginal = pd.DataFrame(margin_data_bucket)

df_marginal

df_marginal.to_csv("aeso_system_marginal_price_report.csv", index = False)

"""## Single Batch Bulk Loads of AESO REST API Data (Asset List, Participant List, Supply/Demand, etc...)"""

# Calling the AESO Assets List API Endpoint for Data
assets_api_response = requests.get(assets_url, headers=headers)    # Calling the Assets Endpoint URL with GET to Obtain AESO Assets List

print("API Call STATUS CODE --", assets_api_response.status_code)  # Printing Out the GET Request Status Code (200 = Good | Else = Didn't Work)
print(assets_api_response.text)                                    # Printing Out the Text Log from Get Request (If 200 Didn't Pop Up before then this tells you what went wrong)

# Converting the Raw Request Format into JSON Format
assets_api_data = assets_api_response.json()

df_assets = pd.DataFrame(assets_api_data['return'])

df_assets

df_assets.to_csv("aeso_assets_list.csv", index = False)

# GET Request to AESO Current Supply Demand Endpoint URL for Data
csd_api_response = requests.get(supplydemand_url, headers=headers)

print("API Call STATUS CODE --", csd_api_response.status_code)
print(csd_api_response.text)

# Converting Obtained GET Requested Data into JSON
csd_api_data = csd_api_response.json()

for thing in csd_api_data['return']:
  print(thing)

csd_api_data['return']

df_csd = pd.json_normalize(csd_api_data['return'], record_path ='generation_data_list')

df_csd



# GET Request to AESO Pool Participants List Endpoint URL for Data
pool_api_response = requests.get(pool_list_url, headers=headers)

print("API Call STATUS CODE --", pool_api_response.status_code)
print(pool_api_response.text)

# Converting Obtained GET Requested Data into JSON
pool_api_data = pool_api_response.json()

df_pool = pd.json_normalize(pool_api_data['return'])

df_pool

df_pool.to_csv("aeso_participant_pool_list.csv", index = False)

"""##AESO Energy Merit Order Report (EMOR) REST API Code Block - UNDER CONSTRUCTION CURRENTLY - SAVING FOR LAST SINCE SCRAPING ALL DATA WILL TAKE APPROXIMATELY 7.5 HOURS"""

# GET Request to AESO Energy Merit Order Report Endpoint URL for Data

data_start_date = datetime(2011, 1, 1)                 # Establishing the Start Date (Start Collecting Data from this Date -- Year, Month, Day)
data_end_date = datetime(2026, 2, 26)                  # Establishing the End Date (Stop Collecting Data at this Date -- Year, Month, Day)

emor_data_bucket = []                                    # Creating a Data Bucket to Store from API Outputs (In this case Data from Actual Forecast Report)

current_date = data_start_date                         # Current 'Indexer' for the Dates. Date-Index Begins at Established Start Date

while current_date < data_end_date:                    # While Loop to Automate Multiple-API Requests for Data

  if current_end > data_end_date:                      # If Condition Made to Clamp Down on 'Date Out of Bounds Error' (aka - do not go beyond the established end date)
    current_end = data_end_date                        # If the index is beyond the end date then clamp down the index to the end date itself which will terminate the loop

  api_params = {                                       # This Dictionary Holds Required API Parameters Used for Requests
      'startDate': current_date.strftime("%Y-%m-%d"),  # Parameter Input - Current Date the Indexer is on
  }

  api_response = requests.get(merit_url, headers=headers, params=api_params)       # Calling the Assets Endpoint URL with GET to Obtain AESO Actual Forecast Reports (2011-2026)

  print("API Call STATUS CODE --", api_response.status_code)                       # Printing Out the GET Request Status Code (200 = Good | Else = Didn't Work)

  if api_response.status_code != 200:                                       # If Condition Made to Catch Request-Errors
    print(api_response.text)                                                # If There's a Request Error then this will print out why there is an error

  else:                                                                     # Else-Branch - Code comes back 200, request is good, data is coming in
    print("Throwing Data into Bucket")                                      # Re-Assuring the User that It is indeed working
    api_data = api_response.json()                                          # API Response is converted to JSON format and stored in variable
    emor_data_bucket.extend(api_data['return']['data'])                     # Data Entries from API Output to JSON is Stored in a Data Collections Bucket

  time.sleep(3)                                                             # Time Delay Established to Not Overwhelm the API Endpoint from Massive Request Calls (3 Second Delay per Request)

  current_date = current_date + timedelta(days=1)                           # Current Index Date Advances by 1-Day before the next batch request

  print(api_params)                                                         # DEBUGGING PURPOSES ONLY -- Just Checking to see if the Date Iteration Actually Works as Intended

test_df = pd.json_normalize(emor_data_bucket, record_path='energy_blocks', meta=['begin_dateTime_utc', 'begin_dateTime_mpt'])

test_df

"""##Testing Around Filtering Specifically for Solar"""

# Digging into the Assets Data and Filtering for Solar Facilities and Assets
counter = 0                                    # Counter Initialized - Here to Quick Tally How Many Asset Names

for thing in assets_api_data['return']:        # Looping Through the Response-Data from JSON

  if 'solar' in thing['asset_name'].lower():   # If Condition for Catching 'solar' in the Asset Names
    print(thing['asset_name'])                 # Displaying the Name of the Asset in which it contained 'solar'
    counter += 1                               # Counter is Incremented Upon Finding a Match

print("Total Count:", counter)                 # The Tally is Printed

# Digging Through Same Assets List Data but Cross-Referencing with 'Pool Participant Name'

solar_name_list = []                                            # Created a List Primarily to Tally the Names Again for Cross-Referencing

for thing in assets_api_data['return']:                   # Loop Created - Going Through the Response Entries in the JSON like before

  if 'solar' in thing['pool_participant_name'].lower():   # Searching for Solar in the names again

    if thing['pool_participant_name'] in solar_name_list:       # This is just to check if the name already exists in the list to prevent duplicates
      continue                                            # Continues On if the Name Already Exists

    else:                                                 # Else Branch
      solar_name_list.append(thing['pool_participant_name'])    # If the Name isn't found there then append it to the name list

print("Total Count:", len(solar_name_list))                     # Print the length of the list as the total tally of found 'Solar' participant names,

for name in solar_name_list:                 # Take the List and Print those Found Names
  print(name)

""" The cross referencing is really just to make sure that there aren't any hidden entries that could pertain to solar. For example, if an asset name had no solar in
it but participant name did. Or vice-versa, where the asset name has solar in the title but participant name doesn't. This sort of deal. In this case, it is a mismatch
of 1 where asset name is 26 and participants is 27. I think this could probably be that 1 asset is registered as 2 names in the market pool as particpants... why?...
It's a mystery of the unknown I guess lol... """

print() # This is just here to prevent the above comment from displaying in the output terminal

