# -*- coding: utf-8 -*-
"""streamlit_testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVlUVBjJcR-Ma9myht_h6ErFVL8E8qq4
"""

!pip install streamlit

# Import Pool
import streamlit as st

st.write("Testing Writing Command")

value = st.slider("Choose a Number:", 0, 100, 50)

st.write("You have Selected:", value)